### PR TITLE
Added some basic CSS styles.

### PR DESCRIPTION
**Pull request by Sahil2004**
This was just a fix for the future pulls.

### CODE REVIEW

**Comment by Sahil2004** [comment]
This was improvements to the bottom box of the website.

**Comment by Sahil2004** [comment]
Some improvements to second box.

**Comment by Sahil2004** [comment]
Some improvements to main div. Made it look like a banner and centered text.

**Comment by Sahil2004** [comment]
Now, here is the final result:
image

**Comment by rjitsu** [comment]
> Now, here is the final result:
> image

I like what you did,but by improvements I meant maybe animations and other fancy stuff.
I like the way it fills the whole page rather than the content being in center 
I'll add contribution guidelines so that this confusion doesn't happen.
Thank you!

**Comment by rjitsu** [comment]
In case if you have some other contributions,you're welcome!As of now I'm closing this PR

**Pull request closed without merging**
